import Head from 'next/head'
import Layout from '../components/Layout'
import Hero from '../components/Hero'
import FeaturesSection from '../components/FeaturesSection'
import CallToAction from '../components/CallToAction'
import { NextSeo } from 'next-seo';


export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <NextSeo
      title="Simple Usage Example"
      description="A short description goes here."
    /> */}

    <Layout> 
      <Hero></Hero>
      <FeaturesSection></FeaturesSection>
      <CallToAction/>
      
      
      </Layout>
      </div>
  )
}
